name: helper_set
description: This package contains many frequently used helper classes, models, and widgets.
version: 0.0.8
homepage: https://github.com/IkhwanSI13/helper_set

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  path_provider: ^2.0.1
  flutter_image_compress: ^1.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/
